name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: (JDK ${{ matrix.jdk }} / ${{ matrix.os }}) Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: ['8', '11', '16']
#        include:
#          - os: ubuntu-latest
#            jdk: '16'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Build
        timeout-minutes: 2
        run: mvn verify
